### ISSUE TITLE
Initial Concept Design - V1

### ISSUE THREAD

**Issue by zhangyuzhan** [deco3500/factopia#12]
## Tasks
- [x] Design the planet
- [x] Design the comment section
- [x] Design another style for main page

**Comment by zhangyuzhan** [comment]
Do you like the background for the main page?
