### ISSUE TITLE
Invision Prototype

### ISSUE THREAD

**Issue by khoiphan21** [deco3500/factopia#23]
## Tasks
- [ ] Static main page
- [ ] Static home page
- [ ] Static page for 1 headline
- [ ] Make the above 3 pages more dynamic and interactive
- [ ] Fake 5 more headlines
- [ ] Fake 10 more 'friends'
- [ ] At least 3 comments for each headline
